spring:
  datasource:
    url: jdbc:db2://d5456ces.456al.b456x.net:5600/BL6
    username: eg5yy
    password: 345rtrhrth

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#
#    properties:
#      hibernate:
#        format_sql: true
#        database-platform: org.hibernate.dialect.DB2400Dialect
#        naming:
#          strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8088
  servlet:
    contextPath: /workflow-center

activiti:
    database-schema: BLUDB
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false  # 自动部署验证设置:true-开启（默认）、false-关闭
    
logging:  path: C:\Users\XinBinCui\CUIXINBIN\logs
